### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by jericopulvera** [faustbrian/Laravel-Commentable#15]
- PHP Version: 7.08
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'BrianFaust\ServiceProvider\ServiceProvider' not found

**Comment by noxify** [comment]
already fixed but not released :)

https://github.com/faustbrian/Laravel-Commentable/commit/c6193e1ce471b1b364033ab9b7151f7be7e7cfb6
