### ISSUE TITLE
 Trait 'BrianFaust\Commentable\HasComments' not found

### ISSUE THREAD

**Issue by jdfx** [faustbrian/Laravel-Commentable#17]
- Version: Laravel 5.3
- PHP Version: 5.6

## Expected behavior:
Trait is found.

## Actual behavior:
Trait is not found..

## Steps to reproduce the behavior:
composer require faustbrian/laravel-commentable
Add BrianFaust\Commentable\CommentableServiceProvider::class to config/app.php
php artisan vendor:publish --provider="BrianFaust\Commentable\CommentableServiceProvider" && php artisan migrate

Add Trait to Model definitions use BrianFaust\Commentable\HasComments;

Then use HasComments;

And error..

**Comment by jdfx** [comment]
The name of the trait in your documentation is wrong.

It should be:

use BrianFaust\Commentable\HasCommentsTrait;

use HasCommentsTrait;

**Comment by tomiiide** [comment]
Try using it like this in your models

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use BrianFaust\Commentable\HasCommentsTrait;
use BrianFaust\Commentable\Interfaces\HasComments;

class Post extends Model implements HasComments
{
  use HasCommentsTrait;
}
```
