### ISSUE TITLE
Creating child comment causes child to be parent to target parent comment

### ISSUE THREAD

**Issue by PunchRockgroin** [faustbrian/Laravel-Commentable#23]
- Version: ^2.1
- PHP Version: 7.1.1

## Expected behavior:
Threading comments, using $parent as outlined, to mark parent_id value of new comment to parent id

## Actual behavior:
New comment becomes the parent instead.

## Steps to reproduce the behavior:
Using the steps here: https://github.com/faustbrian/Laravel-Commentable#create-a-comment-as-a-child-of-another-comment-eg-an-answer

## Proposed solution:
Shouldn't the parent be the one appending node? 

https://github.com/faustbrian/Laravel-Commentable/blob/2566f2149505903f1d4892de566371f406387581/src/HasComments.php#L71-L73

Change to:
As seen here: https://github.com/lazychaser/laravel-nestedset#appending-and-prepending-to-the-specified-parent
`
// #2 Using parent node
$parent->appendNode($comment);
`

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/commit/1813a4ce1b9f867d68b1c7a1848a8e333fd160eb
