### ISSUE TITLE
vendor:publish doesn't publish or run migration (laravel 5.3.31)

### ISSUE THREAD

**Issue by wisdom-17** [faustbrian/Laravel-Commentable#28]
- Version: 2.0
- PHP Version: 5.6

## Actual behavior:
Nothing to publish for tag [].
Nothing to migrate.

## Steps to reproduce the behavior:
composer require faustbrian/laravel-commentable

**Comment by lukasjarosch** [comment]
Did you register the ServiceProvider in **app.php**?
`BrianFaust\Commentable\CommentableServiceProvider::class,`

**Comment by rajjanorkar** [comment]
HI @lukasjarosch  need to put that in installation steps.

**Comment by faustbrian** [comment]
I removed this note on purpose because I am slowly preparing all my packages for Laravel 5.5 which no longer requires manual registration of Service Providers.

**Comment by wisdom-17** [comment]
Thank you @lukasjarosch. That addressed my issue.
