### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by JinjiGomez** [faustbrian/Laravel-Commentable#30]
- Laravel Version: 5.4
- PHP Version: 7.0 / 5.6

## Expected behavior:
Successfully install Laravel commentable

## Actual behavior:

Using version ^2.0 for faustbrian/laravel-commentable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - faustbrian/laravel-commentable 2.1.4 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.
    - faustbrian/laravel-commentable 2.1.3 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.
    - faustbrian/laravel-commentable 2.1.2 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.
    - faustbrian/laravel-commentable 2.1.1 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.
    - faustbrian/laravel-commentable 2.1.0 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.
    - Conclusion: don't install faustbrian/laravel-commentable 2.0.2
    - Conclusion: don't install faustbrian/laravel-commentable 2.0.1
    - Conclusion: remove laravel/framework v5.4.27
    - Installation request for faustbrian/laravel-commentable ^2.0 -> satisfiable by faustbrian/laravel-commentable[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4].
    - Conclusion: don't install laravel/framework v5.4.27
    - faustbrian/laravel-commentable 2.0.0 requires illuminate/database 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/database[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/database v5.1.1|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.13|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.16|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.2|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.20|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.22|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.25|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.28|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.30|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.31|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.41|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.6|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.1.8|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.0|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.19|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.21|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.24|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.25|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.26|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.27|don't install laravel/framework v5.4.27
    - don't install illuminate/database v5.2.28|don't install laravel/framework v5.4.27

How can I successfully install laravel commentable?
It doesnt work on both php 7.0 and 5.6

**Comment by faustbrian** [comment]
It clearly states the issue under problems.

- faustbrian/laravel-commentable 2.1.4 requires php ^7.1 -> your PHP version (7.0.10) does not satisfy that requirement.

My packages do not support anything lower than 7.1

**Comment by JinjiGomez** [comment]
Sorry, I thought it would work since you composer.json says:

    "require": {
        "php": "^7.0",
        "illuminate/support": "5.3.* || 5.4.* || 5.5.*",
        "illuminate/database": "5.3.* || 5.4.* || 5.5.*",
        "kalnoy/nestedset": "^4.1"
    },

My bad. Thank you for your clarification.

**Comment by faustbrian** [comment]
That is a work-in-progress and not the tagged release.
