### ISSUE TITLE
Can i Use this For Multi Auth User?

### ISSUE THREAD

**Issue by codeitlikemiley** [faustbrian/Laravel-Commentable#31]
Lets Say i Have a User table, Employee table and Client Table...
All Have a been properly configure in config/auth.php

to provide a guard 
user is default as web
and additional guard is employee and client...

I wanna know if it only accepts the user model or can accept other Model 
that is the same as the User model...

thanks for reply

**Comment by faustbrian** [comment]
A quick look at the code would have shown you that the `creator` is morphed, meaning it doesn't matter who or what the `creator` it.

https://github.com/faustbrian/Laravel-Commentable/blob/master/database/migrations/create_comments_table.php#L25

**Comment by codeitlikemiley** [comment]
how can i use this trait?

**Comment by faustbrian** [comment]
Read the file called README

**Comment by codeitlikemiley** [comment]
I tried making a trait  for this...
```
<?php 

namespace App\Traits\Permissions;

use BrianFaust\Commentable\Comment;

trait CanComment
{
    // This Trait Needs to Be Added to User, Employee and Clients
    // Since a User, Employee, Client Can Comment
    public function comments()
    {
        return $this->morphMany(Comment::class, 'creator');
    }
}
```

Hope You Can Also Put a Trait for The Person Who Can Comment or the Creator...

thanks
