### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by sml2h3** [faustbrian/Laravel-Commentable#32]
- Version: 5.7
- PHP Version: 7.0

php artisan vendor:publish

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  parse error, expecting `';'' or `'{''

**Comment by faustbrian** [comment]
You’re welcome to send a PR to fix it.

**Comment by sml2h3** [comment]
laravel log
[2017-07-14 09:21:19] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'parse error, expecting `';'' or `'{''' in /Users/wenanzhe/PhpstormProjects/yyk/vendor/faustbrian/laravel-commentable/src/CommentableServiceProvider.php:24
Stack trace:
#0 {main}

**Comment by LINKeRxUA** [comment]
Laravel Framework 5.5.14
"Your requirements could not be resolved to an installable set of packages."

**Comment by redenmiranda** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class '' not found

**Comment by erstefan** [comment]
@faustbrian when trying to migrate I'm getting the same error as @redenmiranda .
I'm using Laravel 5.5. 

How should I go about migrating the table? Any input on this would be greatly appreciated.

**Comment by redenmiranda** [comment]
@erstefan try manually adding timestamps on migration files after publishing. that worked for me

**Comment by erstefan** [comment]
Yeah, I eventually ended up manually creating the migration for comments table.

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/commit/1a99d132b701ebe354fa5b5dad2f1d079b656386
