### ISSUE TITLE
Commentable service provider error

### ISSUE THREAD

**Issue by leonelngande** [faustbrian/Laravel-Commentable#41]
Hi,
I have been developing on Windows and whenver i switch to my Linux install i get this error when i run my project;

`Declaration of BrianFaust\Commentable\CommentableServiceProvider::boot(): BrianFaust\Commentable\void must be compatible with BrianFaust\ServiceProvider\AbstractServiceProvider::boot(): BrianFaust\ServiceProvider\void`

I am on Ubuntu 16.04
Laravel 5.4 

Here's a screenshot

![screenshot from 2017-12-02 07-15-26](https://user-images.githubusercontent.com/13051253/33512428-a56e1446-d730-11e7-92ef-05fb43c31325.png)

**Comment by faustbrian** [comment]
Looks like an old php version.

**Comment by leonelngande** [comment]
I use php 7, here's my CLI output:
`PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )'

**Comment by leonelngande** [comment]
Upgrading to PHP 7.1 fixed it
