### ISSUE TITLE
Add support for Laravel 5.6

### ISSUE THREAD

**Issue by Livijn** [faustbrian/Laravel-Commentable#42]
Hey, right now, only 5.4.* and 5.5.* are supported in the composer.json. Can you add support for 5.6?

`faustbrian/laravel-commentable v3.1.0 requires illuminate/support 5.4.* || 5.5.*`

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/releases/tag/v3.1.1
