### ISSUE TITLE
"Creator" morph columns not respecting Morph Map

### ISSUE THREAD

**Issue by benjivm** [faustbrian/Laravel-Commentable#51]
Hello, this is a strange one, in the migration the following morph columns are created:
```
$table->morphs('commentable');
$table->morphs('creator');
```

Which correspond to these columns:
```
commentable_type
commentable_id
creator_type
creator_id
```

In my `AppServiceProvider` I define a `morphMap()` for all of my app's models:
```
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        Relation::morphMap([
            'categories' => \App\Category::class,
            'epicor_contacts' => \App\EpicorContact::class,
            'users' => \App\User::class,
    ... etc.
```

The `commentable_type` column respects this map, however the `creator_type` column does not, e.g., it displays `App\User` instead of `users`.

Any idea how to fix this?

**Comment by nguyentranchung** [comment]
@benjivm here is key for you
https://github.com/faustbrian/Laravel-Commentable/blob/ef3ad9b2a76e465e430ae4ba25d46b77259f3202/src/Models/Comment.php#L64

**Comment by benjivm** [comment]
Thanks @nguyentranchung I created a [pull request](https://github.com/faustbrian/Laravel-Commentable/pull/52) to fix this.

**Comment by benjivm** [comment]
#52 thanks @faustbrian !
