### ISSUE TITLE
Artisan Publish on Laravel 5.3: Can't locate path

### ISSUE THREAD

**Issue by suretarget** [faustbrian/Laravel-Commentable#8]
**php artisan vendor:publish is failing with:**
Can't locate path: var/www/domain.com/vendor/faustbrian/laravel-commentable/src/../../../resources/config/commentable.php

**Comment by faustbrian** [comment]
Update with some other changes is coming later today.

**Comment by suretarget** [comment]
@faustbrian, I have updated to version 2. When I run php artisan vendor:publish I got error,
Class 'BrianFaust\Commentable\ServiceProvider' not found.

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/commit/9c794433d135c9451a7dc0d33d04770e5ff4612b#diff-04c6e90faac2675aa89e2176d2eec7d8R21

**Comment by suretarget** [comment]
I updated providers now I got FatalErrorException

Illuminate\Support\ServiceProvider::mergeConfigFrom(): Failed opening required '/path/to/vendor/faustbrian/laravel-commentable/src/../resources/config/commentable.php'

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/releases/tag/2.0.1
