### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by suretarget** [faustbrian/Laravel-Commentable#9]
I setup a Model as in documentation and create a comment.
I get this error: **Trait 'BrianFaust\Commentable\HasCommentsTrait' not found**

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Commentable/releases/tag/2.0.2

**Comment by suretarget** [comment]
Thanks for the quick update @faustbrian.
Btw, in documentation $post->getCommentCount() should be updated to  $post->commentCount() instead;
